//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallMarketTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersSupplier
    {
        public CustomersSupplier()
        {
            this.PurchaseSellInvoices = new HashSet<PurchaseSellInvoice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> DiscountPurchasing { get; set; }
        public Nullable<decimal> DiscountSelling { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual ICollection<PurchaseSellInvoice> PurchaseSellInvoices { get; set; }
        public virtual CustomerSuppliertype CustomerSuppliertype { get; set; }
    }
}
