//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallMarketTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmallMarketDBEntities : DbContext
    {
        public SmallMarketDBEntities()
            : base("name=SmallMarketDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<CustomersSupplier> CustomersSuppliers { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<PurchaseSellInvoceDetail> PurchaseSellInvoceDetails { get; set; }
        public DbSet<PurchaseSellInvoice> PurchaseSellInvoices { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<CustomerSuppliertype> CustomerSuppliertypes { get; set; }
    }
}
