//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallMarketTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSellInvoice
    {
        public PurchaseSellInvoice()
        {
            this.PurchaseSellInvoceDetails = new HashSet<PurchaseSellInvoceDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CustomerSupplierId { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public string OrderNo { get; set; }
    
        public virtual CustomersSupplier CustomersSupplier { get; set; }
        public virtual ICollection<PurchaseSellInvoceDetail> PurchaseSellInvoceDetails { get; set; }
    }
}
